---
title: "Project Proposal"
author: "Stefan Schmidt"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Project Topic

The topic of my project will be the *Mortality Fluctuation 2015 - 2022*.

I plan to compare COVID-19 with non-COVID years and also different countries with
each other.

Mortality changes during the year, with usually higher rates in winter. During
the pandemic, certain groups claimed the impact of the SARS-CoV-2 virus was no
greater than that, of the 2017 influenza epidemic in Europe.

Hopefully I can visualize mortality changes over year and provide some figures
that allow to compare different years and/or countries.


## Data Sources


The project will be based on the following data:

* [Short-Term Mortality Fluctuations (STMF)](https://www.mortality.org/Data/STMF)
  data set available at [www.mortality.org](https://www.mortality.org). STMF is
  an international database providing open-access harmonized, uniform, and fully
  documented data on weekly all-cause mortality.
* Country names and three letter country codes (alpha-3) provided by Luke
  Duncalfe available on
  [GitHub](https://github.com/lukes/ISO-3166-Countries-with-Regional-Codes).


## Description of the Data

Please provide specific details about your data.
 
* If the data covers a timespan, what is the time period?
* If the data covers a geographical location, what geographical location(s)?
* If the data is about a business, political, or non-governmental entity or
  activity, which entities or activities does it cover? For example is the data
  about economics, schools, politics, sports, or something else?
* What characteristics are captured by the data? For example, if your data is
  about cities, what characteristics of the cities are captured in the data?
  Population, crime rates, economic measures, business activity, traffic?
* Assuming your data is rectangular (like a spreadsheet), how many rows and
  columns are in the dataset? If your data is not rectangular, how are you going
  to create a "tidy" dataset from these data?


## Ideas about the figures that you will create to visualize this data:

Please provide ideas for the figures you are going to generate from these data.
Are you going to make line plots, bar charts, density plot, dumbbell charts,
choropleths, or what? You should provide a description of at least three
figures. Your final project will include eight figures.



## References 

HMD. Human Mortality Database. Max Planck Institute for Demographic Research
(Germany), University of California, Berkeley (USA), and French Institute for
Demographic Studies (France). Available at
[www.mortality.org](https://www.mortality.org) (data downloaded on 19-Jul-2022).

