---
title: "Mortality"
author: "Stefan Schmidt"
date: "`r Sys.Date()`"
output: 
    flexdashboard::flex_dashboard:
        orientation: columns
        vertical_layout: fill
        source_code: "embed"
runtime: shiny
---

```{r setup, include=FALSE, cache=TRUE}
library(flexdashboard)
library(tidyverse)
library(lubridate)
library(plotly)
library(shiny)

countries <- tribble(
~CountryCode, ~Country,
"AUS",        "Australia",
"AUT",        "Austria",
"BEL",        "Belgium",
"BGR",        "Bulgaria",
"CAN",        "Canada",
"CHL",        "Chile",
"HRV",        "Croatia",
"CZE",        "Czechia",
"DNK",        "Denmark",
"GBRTENW",    "England & Wales",
"EST",        "Estonia",
"FIN",        "Finland",
"FRATNP",     "France",
"DEUTNP",     "Germany",
"GBR_SCO",    "Scottland",
"ESP",        "Spain",
"GRC",        "Greece",
"HUN",        "Hungary",
"ISL",        "Iceland",
"ISR",        "Israel",
"ITA",        "Italy",
"KOR",        "Korea",
"LVA",        "Latvia",
"LTU",        "Lithuania",
"LUX",        "Luxembourg",
"NLD",        "Netherlands",
"NZL_NP",     "New Zealand",
"GBR_NIR",    "Northern Ireland",
"NOR",        "Norway",
"POL",        "Poland",
"PRT",        "Portugal",
"RUS",        "Russia",
"SVK",        "Slovakia",
"SVN",        "Slovenia",
"SWE",        "Sweden",
"CHE",        "Switzerland",
"TWN",        "Taiwan",
"USA",        "USA"
)

stmf_url <- 
  "https://mortality.org/File/GetDocument/Public/STMF/Outputs/stmf.csv"
df <- read_csv(url(stmf_url), skip = 2)

df <- df %>% 
  dplyr::left_join(countries, by = "CountryCode") %>% 
  relocate("Country")

countries <- df %>%
  select(Country) %>% 
  unique() %>% 
  arrange(Country)
```

CRD (yearly)
======

Input{.sidebar}
----------------------------------------------------------------

```{r in-cdr-countries}
selectInput(
  inputId = "cdrCountries",
  label = "Compare multiple Countries:",
  choices = countries,
  selected = c("Germany", "New Zealand", "Sweden", "Switzerland", "USA"),
  multiple = TRUE)
```


Column{data-height=750}
----------------------------------------------------------------

### Crude Death Rate (yearly)

```{r plot-cdr}
renderPlot(
  df %>% 
  filter(Country %in% input$cdrCountries, Sex == "b") %>% 
  mutate(
    population = DTotal / RTotal,
    Year = ymd(Year, truncated = 2)) %>% 
  group_by(Year, Country) %>% 
  summarise(CDR = sum(DTotal) / sum(population) * 10^3, .groups = "drop") %>% 
  ggplot(aes(x = Year, y = CDR, color = Country)) +
  geom_line(size = 1) +
  labs(
    title = "Deaths per Year and 1000 Inhabitants",
    y = "Deaths / Year and 1000 Inhabitants")
)
```

CRD (weekly)
======

Input{.sidebar}
----------------------------------------------------------------

```{r in-wdr-country}
selectInput(
  inputId = "wdrCountry",
  label = "Select Country:",
  choices = countries,
  selected = "Switzerland")
```


```{r in-wdr-years}

selectInput(
  inputId = "wdrYears",
  label = "Compare multiple Years:",
  choices = 2016:2022,
  selected = c(2020, 2021),
  multiple = TRUE)
```


Column{data-height=750}
----------------------------------------------------------------

### Crude Death Rate (weekly)

```{r plot-wdr}
renderPlot(
  df %>% 
  filter(Year %in% input$wdrYears,
         Country == input$wdrCountry,
         Sex == "b") %>% 
  mutate(Year = factor(Year)) %>% 
  group_by(Year, Country) %>% 
  ggplot(aes(x = Week, y = RTotal * 10^3, color = Year)) +
  geom_line() +
  labs(
    title="Deaths per Year and 1000 Inhabitants",
    x="Week of Year",
    y="Deaths / Year and 1000 Inhabitants")
)
```


Absolute Death Rates
======

Input{.sidebar}
----------------------------------------------------------------

```{r in-age-country}
selectInput(
  inputId = "ageCountry",
  label = "Select Country:",
  choices = countries,
  selected = "Switzerland")
```


```{r in-age-years}

selectInput(
  inputId = "ageYear",
  label = "Select Year:",
  choices = 2016:2022,
  selected = 2020)
```


Column{data-height=750}
----------------------------------------------------------------

### Mortality by Age Group

```{r plot-age}
renderPlot(
  df %>% 
  filter(Country == input$ageCountry,
         Year == input$ageYear,
         Sex == "b") %>% 
  select(Country, Year, Week, D0_14, D15_64, D65_74, D75_84, D85p) %>% 
  pivot_longer(
    cols = starts_with("D"),
    names_to = "Age",
    names_prefix = "D",
    values_to = "Deaths") %>% 
  mutate(Age = recode(Age,
                      `0_14` = "0 - 14 years",
                      `15_64` = "15 - 64 years",
                      `65_74` = "65 - 74 years",
                      `75_84` = "75 - 84 years",
                      `85p` = "85+ years")) %>% 
  mutate(Age = factor(Age)) %>% 
  ggplot(aes(Week, Deaths, fill = Age)) +
    geom_area(position = position_stack(reverse = TRUE)) +
    labs(
    title="Death Rates",
    subtitle="Absolute Numbers by Age Group",
    x="Week of Year",
    y="Deaths / Week") +
    guides(fill = guide_legend(reverse=T))
)
```




### Mortality by Sex

```{r bar-plot-sex}
renderPlot(
  df %>% 
  filter(Country == input$ageCountry,
         Year == input$ageYear,
         Sex != "b") %>% 
  select(Country, Year, Week, Sex, DTotal) %>% 
  mutate(Sex = recode(Sex,
                      `f`="female",
                      `m`="male")) %>% 
  ggplot(aes(Week, DTotal, fill = Sex)) +
  geom_area() +
    labs(
    title="Death Rates",
    subtitle="Absolute Numbers by Sex",
    x="Week of Year",
    y="Deaths / Week")
)
```


Relative Death Rates
======

Input{.sidebar}
----------------------------------------------------------------

```{r in-rage-country}
selectInput(
  inputId = "rageCountry",
  label = "Select Country:",
  choices = countries,
  selected = "Switzerland")
```

```{r in-rage-year}
selectInput(
  inputId = "rageYear",
  label = "Select Year:",
  choices = 2016:2022,
  selected = 2020)
```


Column{data-height=750}
----------------------------------------------------------------

### Relative Death Rate by Age

```{r plot-rage}
renderPlot(
  df %>% 
  filter(Country == input$rageCountry,
         Year == input$rageYear,
         Sex == "b") %>% 
  select(Country, Year, Week, R0_14, R15_64, R65_74, R75_84, R85p) %>% 
  pivot_longer(
    cols = starts_with("R"),
    names_to = "Age",
    names_prefix = "R",
    values_to = "DeathRate") %>% 
  mutate(Age = recode(Age,
                      `0_14` = "0 - 14 years",
                      `15_64` = "15 - 64 years",
                      `65_74` = "65 - 74 years",
                      `75_84` = "75 - 84 years",
                      `85p` = "85+ years",
                      `Total` = "all ages")) %>% 
  mutate(Age = factor(Age)) %>% 
  ggplot(aes(Week, DeathRate, color = Age)) +
    geom_line() +
    labs(
    x="Week of Year",
    y="relative Death Rate") +
    guides(color = guide_legend(reverse=T))
)
```


### Death Rate by Sex

```{r plot-rsex}
renderPlot(
  df %>% 
  filter(Country == input$rageCountry,
         Year == input$rageYear,
         Sex != "b") %>% 
  select(Country, Year, Week, Sex, RTotal) %>% 
  mutate(Sex = recode(Sex,
                      `f`="female",
                      `m`="male")) %>% 
  ggplot(aes(Week, RTotal * 10^3, color = Sex)) +
  geom_line() +
    labs(
    x="Week of Year",
    y="Deaths / Year and 1000 Inhabitants")
)
```



Comparison {data-orientation=columns}
===================================== 

Column
-------

```{r in-cmp-country1}
selectInput(
  inputId = "cmpCountry1",
  label = "Select first Country:",
  choices = countries,
  selected = "Switzerland")

selectInput(
  inputId = "cmpYear1",
  label = "Select Year:",
  choices = 2016:2022,
  selected = c(2020, 2021))
```


### Relative Death Rate

```{r splot-1st-cntry}
renderPlot(
  df %>% 
  mutate(Year = factor(Year)) %>% 
  filter(Country == input$cmpCountry1,
         Year == input$cmpYear1,
         Sex == "b") %>% 
  select(Country, Year, Week, RTotal) %>% 
  ggplot(aes(Week, RTotal * 10^3)) +
  geom_point() +
  labs(y="Deaths / Year and 1000 Inhabitants",
       x="Week of Year") +
  guides(color="none")
)
```

### Distribution by Sex

```{r hist-1st-cntry}
renderPlot(
  df %>% 
  mutate(Year = factor(Year)) %>% 
  filter(Country == input$cmpCountry1,
         Year == input$cmpYear1,
         Sex != "b") %>% 
  select(Country, Year, Week, Sex, RTotal) %>% 
  mutate(Sex = recode(Sex,
                      `f`="female",
                      `m`="male")) %>% 
  ggplot(aes(Sex, RTotal * 10^3, fill=Sex)) +
  geom_boxplot() +
  labs(y="Deaths / Year and 1000 Inhabitants") +
  guides(fill="none")
)
```

Column
-------

```{r in-cmp-country2}
selectInput(
  inputId = "cmpCountry2",
  label = "Select second Country:",
  choices = countries,
  selected = "Germany")

selectInput(
  inputId = "cmpYear2",
  label = "Select Year:",
  choices = 2016:2022,
  selected = c(2020, 2021))
```


### Relative Death Rate

```{r splot-2nd-cntry}
renderPlot(
  df %>% 
    mutate(Year = factor(Year)) %>% 
    filter(Country == input$cmpCountry2,
           Year == input$cmpYear2,
           Sex == "b") %>% 
    select(Country, Year, Week, RTotal) %>% 
    ggplot(aes(Week, RTotal * 10^3)) +
    geom_point() +
    labs(y="Deaths / Year and 1000 Inhabitants",
         x="Week of Year") +
    guides(color="none")
)
```

### Distribution by Sex

```{r hist-2nd-cntry}
renderPlot(
  df %>% 
    mutate(Year = factor(Year)) %>% 
    filter(Country == input$cmpCountry2,
           Year == input$cmpYear2,
           Sex != "b") %>% 
    select(Country, Year, Week, Sex, RTotal) %>% 
    mutate(Sex = recode(Sex,
                      `f`="female",
                      `m`="male")) %>% 
    ggplot(aes(Sex, RTotal * 10^3, fill=Sex)) +
    geom_boxplot() +
    labs(y="Deaths / Year and 1000 Inhabitants") +
    guides(fill="none")
)

```


